export const authText = {
  welcomeBack: "Tekrar hoşgeldiniz !",
  signInWithGoogle: "Google ile giriş yap",
  dontHaveAccount: "Henüz üye değil misin ?",
  alreadyHaveAccount: "Zaten üye misin ?",
  withEmail: "veya e-posta ile devam et",
  forgotPassword: "Şifreni mi unuttun ?",
  createNewPassword: "Yeni şifre oluştur",
  passwordUpdated: "Şifre güncellendi!",
  passwordUpdatedSubtitle:
    "Şifren başarıyla güncellendi. Artık yeni şifrenle giriş yapabilirsin.",
  createNewPasswordSubtitle:
    "Yeni şifren, eski şifrelerinden farklı olmalıdır.",
  enterEmail:
    "Sorun değil! E-posta adresini gir, sana bir sıfırlama bağlantısı gönderelim.",
  checkEmail: "E-postanı kontrol et",
  checkSpam: `E-postayı almadın mı? Spam klasörünü kontrol et veya birkaç dakika sonra tekrar dene.`,
  signInSubtitle: "Devam etmek için giriş yapın",
  registerTitle: "Hesap Oluştur",
  registerSubtitle: "Bize katıl ve gelinliğini tasarlamaya hemen başla.",
  updatingPassword: "Şifre güncelleniyor...",
  signingIn: "Giriş yapılıyor...",
  sendingLink: "Bağlantı gönderiliyor...",
  creatingAccount: "Hesap oluşturuluyor...",
  buttons: {
    login: "Giriş Yap",
    register: "Hesap oluştur",
    sendResetLink: "Sıfırlama bağlantısını gönder",
    returnLogin: "Giriş ekranına dön",
    updatePassword: "Şifreyi güncelle",
  },
  labels: {
    firstName: "Ad",
    lastName: "Soyad",
    email: "E-posta adresi",
    password: "Şifre",
    confirmPassword: "Şifre tekrar",
    rememberMe: "Beni hatırla",
    forgotPassword: "Şifremi unuttum ?",
    createAccount: "Hesap oluştur",
  },
  placeholders: {
    email: "zozak@gmail.com",
    password: "********",
    confirmPassword: "Şifrenizi tekrar girin",
    firstName: "Adınızı girin",
    lastName: "Soyadınızı girin",
  },
};
