export const authText = {
  welcomeBack: "Welcome back!",
  signInWithGoogle: "Continue with Google",
  dontHaveAccount: "Don't have an account yet?",
  alreadyHaveAccount: "Already have an account?",
  withEmail: "or continue with email",
  forgotPassword: "Forgot your password?",
  createNewPassword: "Create a New Password",
  passwordUpdated: "Password updated!",
  passwordUpdatedSubtitle:
    "Your password was updated successfully. You can now sign in with it.",
  createNewPasswordSubtitle:
    "Your new password must be different from your previous ones.",
  enterEmail:
    "No worries! Enter your email address and we'll send you a reset link.",
  checkEmail: "Check your email",
  checkSpam: `Didn't get the email? Check your spam folder or try again in a few minutes.`,
  signInSubtitle: "Sign in to continue",
  registerTitle: "Create an Account",
  registerSubtitle: "Join us and start designing your gown right away.",
  updatingPassword: "Updating password...",
  signingIn: "Signing in...",
  sendingLink: "Sending link...",
  creatingAccount: "Creating account...",
  buttons: {
    login: "Sign In",
    register: "Create Account",
    sendResetLink: "Send reset link",
    returnLogin: "Back to login",
    updatePassword: "Update password",
  },
  labels: {
    firstName: "First name",
    lastName: "Last name",
    email: "Email address",
    password: "Password",
    confirmPassword: "Confirm password",
    rememberMe: "Remember me",
    forgotPassword: "Forgot password?",
    createAccount: "Create account",
  },
  placeholders: {
    email: "you@example.com",
    password: "Enter your password",
    confirmPassword: "Re-enter your password",
    firstName: "Enter your first name",
    lastName: "Enter your last name",
  },
};
